name: Foo
on:
  push:
    branches: [ $default-branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: siilarsi/upsert-issue
        with:
          title: foo
          body: foo
# Adapted from:
# https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization
